baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'e_Portefolio'
theme = 'iutlens'



[[menu.main]]
name = "CV"
url = "/blog"

[[menu.main]]
name = "Projet"
url = "/projet"

[[menu.social]]
name = "GitHub"
url = "https://github.com/VotreCompteGithub"
pre = "<i class='fab fa-github'></i>"

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/VotreCompteTwitter"
pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
name = "A propos"
url = "/a-propos-de"

[params]
author = "Antonin Riquart"
authorImage = "/images/avatar.jpg"

